# Site settings -----------------------------------
title: 3ème Rive
email: clairezuliani@gmail.com
description: 3ème rive, café associatif en projet à Epinal
logo: # 120x120 px default image used for Twitter summary card
teaser: 'teaser.jpg' # 400x250 px default teaser image used in image archive grid
# baseurl: "/jekyll-starter" # the subpath of your site, e.g. /blog
url: "https://www.3eme-rive.org/" # the base hostname & protocol for your site
feed:
  path: atom.xml

# Social settings ------------------------------------
github_username: clairezed
twitter_username: ZooletteDesBois

# Build settings --------------------------------------
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock

kramdown:
  toc_levels: 1..2
highlighter: rouge


# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  sourcemap: true
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr

# Includes ----------------------------------------------
include:
  - _pages
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

defaults:
  -
    scope:
      path: "_pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "post"
      permalink: /:basename

# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:
