contact_email: contact@3eme-rive.org
seo_title: 3ème Rive
seo_description: 3ème rive, café associatif en projet à Epinal
subscription_link: https://www.helloasso.com/associations/3eme-rive-cafe-associatif/adhesions/adhesions-2020